### ISSUE TITLE
Is there a way to add a single data point to a chart that's already been rendered?

### ISSUE THREAD

**Issue by TheNotary** [ankane/chartkick.js#66] opened 2016-05-26 03:52 UTC
I'd like to update a graph with live data.  I'm working on something like this at the moment:

```
// chart1 is a Chartkick.LineChart
chart1.dataSource.push([new Date("2016-04-25"), 50.50]);

// or maybe like

merge_options(chart1.dataSource, JSON.parse("{\"2016-05-25T00:00:00-07:00\": \"99.99\"}"))

function merge_options(obj1,obj2){
    var obj3 = {};
    for (var attrname in obj1) { obj3[attrname] = obj1[attrname]; }
    for (var attrname in obj2) { obj3[attrname] = obj2[attrname]; }
    return obj3;
}
```

Would there be any interest in a PR for this feature?

**Comment by ankane** [comment] 2016-05-26 04:38
There's no way to do this right now, but a method on `Chartkick.LineChart` would be welcome.

**Comment by TheNotary** [comment] 2016-05-26 06:44
At the moment, I came up with a kind of hackish solution to get by (redraw the chart with the charts existing data, plus an additional datapoint):

```
// This function will take the existing data in chartObject, and add the dataPoint
// to that pre-existing dataset.  Then it creates a brand new chart out of the result
// Parameters:
//   chartObject: An instantiation of Chartkick.LineChart
//   dataPoint:   A JSON hash container any number of Date: Decimal pairs.
//
// example:  addDatapointToChart(chart1, JSON.parse("{\"2016-05-25T00:00:00-07:00\": \"99.99\"}"))
function addDatapointToChart(chartObject, dataPoint) {
  var addition = merge_options(chart1.dataSource, dataPoint);

  chart1 = new Chartkick.LineChart(chartObject.element.id,
    addition
  );
}


/**
 * Overwrites obj1's values with obj2's and adds obj2's if non existent in obj1
 * @param obj1
 * @param obj2
 * @returns obj3 a new object based on obj1 and obj2
 */
function merge_options(obj1,obj2){
    var obj3 = {};
    for (var attrname in obj1) { obj3[attrname] = obj1[attrname]; }
    for (var attrname in obj2) { obj3[attrname] = obj2[attrname]; }
    return obj3;
}
```

Only tested on 430dbc8.

**Comment by elishao** [comment] 2016-11-02 15:17
I'm using multiple series Area and I also needed to update the data interactivily, so as suggested here, I'm redrawing the whole chart again to add data points (just calling Chartkick.AreaChart again).
The problem is that if the user hide one data series, this data series is shown again after the redraw.
any suggestion how to fix this?
Thanks

**Comment by ankane** [comment] 2016-11-03 09:02
Hey @elishao, same situation as earlier.

> There's no way to do this right now, but a method would be welcome.

**Comment by ankane** [comment] 2018-08-07 01:55
Closing out feature requests to clean up GitHub Issues. If there is still interest AND someone wants to add this, please reply and we can continue to discussion.

**Closed by ankane** 2018-08-07 01:55 UTC
Labels: enhancement
